name: Matrix Demo
on: push
jobs:
  build:
    # continue on error because if any of the combinations fail the default behavior is to cancel any remaining jobs, but we want all combinations to run
    continue-on-error: true
    # The matrix will 6 the build job 6 times, using all possible combinations of the node version and operating system
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        # include is a keyword that allows for stand alone configurations
        include:
          - node-version: latest
            operating-system: macos-latest
        # exclude is a keyword that allows for removing stand alone configurations
        exclude:
          - node-version: 12
            operating-system: windows-latest
    # matrix is a keyword that allows you to run a job multiple times with different configurations
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build