# This is an example of a reusable workflow
# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
# The goal is to use this workflow inside other workflows
name: Reusable Deploy
# workflow_call allows you to call a workflow from another workflow
on:
  workflow_call:
    # an input is like a parameter for the workflow
    # so you can pass values to the workflow
    inputs:
      artifact_name:
        description: 'The name of the artifact to download'
        # required means that the input is mandatory
        required: true
        default: dist
        type: string
    # can also pass secrets to the reusable workflow
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: The result of the deployment operation
        # this will get the value from the deploy job outcome line 29 below
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      # this will get the value from the step-result step below
      outcome: ${{ steps.step-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          # here we use the input provided to this workflow
          name: ${{ github.event.inputs.artifact_name }}
      - name: list files
        run: ls
      - name: Output information
        run: echo "deploying & uploading..."
      - name: Set result output
        id: step-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
